fieldLayouts:
  f919f605-9920-4bc0-a87c-4523cb2566b0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c43c1445-f464-4030-b940-3860611762e8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2365e01a-20c7-42cd-866f-4e4a79bca25d # rich text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 40b20664-95d3-45c6-9096-652f0d154fcc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4fd009a8-92e4-4754-a3f0-0b9446e703d4
        userCondition: null
handle: headerTitle
hasTitleField: false
name: 'header title'
section: 12332128-52a9-4990-b53f-ad5bdd81cd4c # header title
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
