fieldLayouts:
  804c1a05-0ef6-4213-bfb2-869337758a87:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 3cbed65d-e6b8-42af-8582-a5df10f8c3a6
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 3b73a910-52d9-4ab5-a254-4e3e852720d4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 322464b6-0fee-4876-9731-59d98b6c6334
        userCondition: null
fs: assets
handle: newsAssets
name: news-assets
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: assets
transformSubpath: ''
