columnSuffix: yprwwwti
contentColumnType: text
fieldGroup: 784b6530-b0a2-46f1-a5cc-008816f6ad32 # Common
handle: introText
instructions: null
name: 'intro text'
searchable: false
settings:
  byteLimit: null
  charLimit: 400
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
