defaultPlacement: end
enableVersioning: true
handle: aboutUs
name: 'About Us'
propagationMethod: all
siteSettings:
  22157584-fdf0-40c9-817d-207e92689d61: # craft-news-a
    enabledByDefault: true
    hasUrls: true
    template: _about.twig
    uriFormat: about-us
type: single
