defaultPlacement: end
enableVersioning: true
handle: headerTitle
name: 'header title'
propagationMethod: all
siteSettings:
  22157584-fdf0-40c9-817d-207e92689d61: # craft-news-a
    enabledByDefault: true
    hasUrls: true
    template: header-title/_entry
    uriFormat: header-title
type: single
