defaultPlacement: end
enableVersioning: true
handle: pluginReviews
name: 'plugin reviews'
propagationMethod: all
siteSettings:
  22157584-fdf0-40c9-817d-207e92689d61: # craft-news-a
    enabledByDefault: true
    hasUrls: true
    template: plugin-reviews/_entry
    uriFormat: 'plugin-reviews/{slug}'
type: channel
