defaultPlacement: end
enableVersioning: true
handle: storeCategories
name: 'Store Categories'
propagationMethod: all
siteSettings:
  22157584-fdf0-40c9-817d-207e92689d61: # craft-news-a
    enabledByDefault: true
    hasUrls: true
    template: store-categories/_entry
    uriFormat: 'store-categories/{slug}'
structure:
  maxLevels: null
  uid: f3ca7f9c-837b-4efb-8710-5be29a15917e
type: structure
